team-16-capstone/main

package-lock.json
package.json
prisma/migrations/20240322155813_/migration.sql
src/lib/prisma.js
src/pages/api/getAllMeats.js

faulty api routes for Anais to check. I also installed next and express.

faulty api routes

---

src/pages/api/getAllMeats.js
src/pages/api/getButchers.js

Deleted old API route, created new one to get butchers. It will check for zipcode being true to return info.

created sample API route for getting butchers.

---

package.json
prisma/index.js
prisma/meatRouter.js
prisma/schema.prisma
src/App.jsx
src/lib/prisma.js

Added API route for getting meats, resolved lib/index.js conflict.

working router!!!

---

prisma/butchersRouter.js
prisma/index.js
src/App.jsx

added butchersRouter

---

package-lock.json
prisma/butchersRouter.js
prisma/index.js
prisma/meatRouter.js
prisma/migrations/20240326152721_/migration.sql
prisma/migrations/20240326162008_/migration.sql
prisma/uniqueMeatRouter.js
prisma/userRouter.js

Updated API routes, they should have the more correct ".../api/____" format. 
Got started on a uniqueMeat route, but it is UNFINISHED, it will NOT work from this pull !!!

Updated apiroutes made incomplete uniqueMeatRouter

---

prisma/uniqueMeatRouter.js

Create uniqueMeatRouter, will find meat based on its id.
NOTE: its endpoint is not properly setup on this push, given the restructuring of index.js and seed.js. Once that's done, an app.use("/api", uniqueMeatRouter will be added and it'll work a-ok!

Created uniqueMeatRouter

---

prisma/index.js

Added POST/PATCH/GET/DELETE routes for our current tables. 
Incorporated next() middleware to handle errors. 
Reorganized routes by type for readability. 
Added relevant commentary.

Added POST/PATCH/GET/DELETE routes.

---

prisma/index.js
vite.config.js

An authenticate function has been created to check if the encrypted password is the same as the given one. It has NOT been connected to frontend yet, don't try to do it. :'-) 
Also configured our vite.config.js file, our vite server will properly listen to our server port (3001) for API calls.

created authenticate function/configured vite

---

package-lock.json
package.json
prisma/index.js

Added incomplete findUserByToken function, imported 'process' on index.js to be able to work with out .env. Issues are popping up with the port, so for now it'll default to port 3001.

Added incomplete finduserbytoken, added processimp

---

prisma/index.js

Added auth function, installed some dependencies.

added auth func

---

generateSecretKey.js
package.json
prisma/index.js

Added POST path, added script to generate secret key.

POST path now generates secret key.

---

prisma/index.js
src/App.jsx
src/components/Login.jsx
src/components/Register.jsx

Added registering functionality to front end. Changed setFirstname in register component to just setName. This can be changed later on so we actually store all their info, once we iron out registering and logging in.

Added registering functionality to front end

---

prisma/index.js
src/App.jsx
src/components/Login.jsx
src/index.css

Login functionality started. Currently broken. :) Feel free to comment out onSubmit in Login component if you want to be redirected to the rest of the site.

started work on login functionality

---

src/App.jsx
src/components/ProtectedRoute.jsx

Authentication is working, still has some kinks:
Check if the token is the correct one, not just any token.
Have the login button on click take you to another page.

Authentication working

---

src/App.jsx

Fixed register function, the endpoint was incorrect.

Fixed register (endpoint was incorrect)

---

src/App.jsx
src/components/Login.jsx
src/components/Register.jsx

Upon logging in with correct credentials, will be redirected  to account page. Registering does NOT redirect yet.

Upon succesfully logging in, will be redirected.

---

prisma/index.js
src/App.jsx
src/components/Login.jsx
src/components/NavBar.jsx
src/components/Register.jsx

Upon registering, user will be redirected to login screen. Logout button will correctly delete token from local storage and redirect to login screen. 
Upon registering with a user that already exists, an error will be logged into the console - this should be changed to display something on the screen!

Registering redirecting functionality added

---

prisma/index.js
src/App.jsx
src/components/ProtectedRoute.jsx

The application correctly authenticates whether the token stored locally is the correct one. Any attempt to access a page without the **correct** token will lead to an error, in which the token in local storage will be removed.

Correctly authenticates user token

---

prisma/index.js

Created middleware to protect certain API routes (delete, post, patch, etc), in order to prevent non-users from accessing them.

Added auth routes to API routes

---

prisma/index.js
src/components/NewExperience.jsx

Fixed auth middleware for API routes. Instruction comments added to the middleware to explain implementation.

Fixed auth middleware

---

prisma/index.js
prisma/schema.prisma
src/App.jsx
src/components/Login.jsx
src/components/PaymentForm.jsx
src/components/StripeContainer.jsx
src/components/StripePayment.jsx

LOTS OF CHANGES! 
A registered user will be required to pay through Stripe before being able to log in. 
A few routes were created to handle this, including checking for the user to make sure they have not already payed for stripe (In which case, it will not allow them to move to Stripe payment) and another to actually update their user status without needing to ask for a password. 
A few QOL changes were also performed.(a link on the login screen to take them to Stripe payment in case they registered but didn't pay, user is redirected to the account page if they're already registered and logged in, the authenticate function in index.js displays more specific errors to take into account Stripe implementation).
Make sure to delete your migration and reseed!

Stripe registration/cleanup

---

.eslintrc.cjs
prisma/index.js
src/App.jsx
src/components/Login.jsx
src/components/PaymentForm.jsx
src/components/Register.jsx
src/components/StripePayment.jsx

Cleaned up code (removed unnecessary imports). 
Fixed a bug where the incorrect login error would persist into "/stripepayment".
Fixed a bug where a user could register with blank data(no email, no password, no name). Now, they require all the fields to have *something*. As I type this, I realize we should require the email to be an actual email, I'll work on that next push. 
Added an on-screen error when inputting incorrect information during stripe payment email verification.

General cleanup, certain errors popup on screen

---

index.html
package.json
prisma/index.js
src/App.css
src/components/Account.jsx
src/components/MeatYourMatch.jsx

Added google maps! It's just the base template, I'll keep working on it. 
Also added a conditional welcome message for the user.

Baby steps on Google Maps, welcome message

---

src/components/Account.jsx
src/components/MeatYourMatch.jsx

Changes to maps, current issue: multiple pins will not show messages. 
Cleaned up account.jsx

maps changes

---

package.json
prisma/index.js

I installed nodemailer! It's a library that will allow us to send our new users an email upon registration. I also added the code in index.js to perform this, I tested it out and it worked.

Added nodemailer

---

prisma/schema.prisma
prisma/seed.js
src/components/MeatYourMatch.jsx

Google Maps code was worked on, now the markers can be clicked to display more information on our butchers. 
Markers change colors to reflect they are being clicked.
Modified zoom and sizing levels for map. 
Reworked butchers model and seeding file to populate our butchers with their latitude and longitudes to make our maps customizable and more easily populated.

gmaps refined - added new div to display info

---

prisma/index.js
prisma/schema.prisma
src/components/MyExperiences.jsx
src/components/NewExperience.jsx
src/components/RatingSystem.jsx

This will require a NPX PRISMA MIGRATE DEV. Updates to the prisma.schema.

ratings implemented

---

prisma/index.js

Updated the outgoing email wording

email wording update

---

prisma/index.js
prisma/schema.prisma
prisma/seed.js
src/components/MeatYourMatch.jsx

schema.prisma has a new model, called MeatButcher. This is a many to many model that allows our butchers to have meats with unique prices. 
A route was created to access these meats (example implementation exists within Meat your Match component). 
Seeding file was modified to seed the MeatButcher model. 
A randomizer was created to randomly generate prices for these meats +/- $2 (with cents), based on avg. prices from those cuts. 
Meat your Match component now renders these prices when clicking the butchers.

Meat your math displays butchers and prices

---

src/components/MeatYourMatch.jsx
src/components/MyExperiences.jsx

Second dropdown created in Meat your Match page. 
Choosing a meat displays only that meat for the selected vendor. 
Squashed a bug where the map marker would change color if clicked, but not if the butcher was selected from the dropdown menu.

Dependent pick list for meats

---

src/App.jsx
src/components/MyExperiences.jsx

Resolved the routing issue, but still working on the 404 error.

Updating routing

---

prisma/index.js
prisma/schema.prisma
src/components/Community.jsx
src/components/MyExperiences.jsx
src/components/NewExperience.jsx
src/components/SingleButcher.jsx

you will need to rebuild your db due to change in schema

reverted picklists change to booleans to meats

---

src/components/MeatYourMatch.jsx

- Upon selecting a meat, and then selecting All butchers, a list of all the prices for that specific meat will display, with a (LOWEST PRICE) span next to the cheapest selection. 
KNOWN ISSUES:
- If you have already selected "All butchers", you cannot automatically select another meat to see their prices. You have to switch to another butcher, and then return to "All butchers". This does not occur when switching meats within an individual butcher. I think adding a Button to filter the results will fix this, instead of them showing up immediately upon selecting a meat and a butcher. 
- I would like for the cheapest butcher to have its marker on the map highlighted, for clarity's sake.

Displays all butchers prices

---

src/components/EditExperience.jsx

-Edit experience correctly works now. 
-Got rid of some unnecessary lines of code so the component itself is cleaner and easier to read. 
-STILL NEEDS THE REST OF THE MEAT ICONS. *

The dreaded edit has been fixed!

---

prisma/index.js
src/components/Account.jsx
src/components/Butchers.jsx
src/components/Community.jsx
src/components/MeatYourMatch.jsx
src/components/MyExperiences.jsx
src/components/NewExperience.jsx
src/components/SingleButcher.jsx
src/utilities/deleteExperience.js
src/utilities/fetchAllButchers.js
src/utilities/fetchAllMeats.js
src/utilities/fetchButcherMeats.js
src/utilities/fetchExperiences.js
src/utilities/fetchSingleButcher.js
src/utilities/fetchUserById.js
src/utilities/postNewExperience.js
src/utilities/verifyToken.js

- Created utilities folder for reusable functions
- Fixed delete experience functionality 
- Delete useless auth props

General cleanup - created utilities directory

---

src/components/MeatYourMatch.jsx

- Reworked Meat Your Match page
- Users now have to refresh selection before changing meat.
- Comparison with other butchers' pricing now exists within the selected butcher, which doesn't display upon initialization for readability's sake.

Reworked meat your match page

---

src/components/MeatYourMatch.jsx

- Added missing state in PositionDetails component

fixed isDetailsOpen state

---

prisma/index.js
src/components/EditExperience.jsx

Cleaned up edit experience, and readied our index.js for heroku deployment.

heroku prep

---

package.json
vite.config.js

Changed script path to take into account /src

changed script path

---

src/components/PaymentForm.jsx
src/components/ProtectedRoute.jsx
src/utilities/deleteExperience.js
src/utilities/fetchAllButchers.js
src/utilities/fetchAllMeats.js
src/utilities/fetchButcherMeats.js
src/utilities/fetchExperiences.js
src/utilities/fetchSingleButcher.js
src/utilities/fetchUniqueExperience.js
src/utilities/fetchUserById.js
src/utilities/patchUserExperience.js
src/utilities/postNewExperience.js
src/utilities/verifyToken.js

Fixed backend endpoints to meet deployment requirements

fixed backend endpoints

---

src/App.jsx
src/components/StripePayment.jsx
vite.config.js

Fixed cleaning up api calls for online database.

Finished changing routes

---

src/utilities/fetchAllMeats.js
src/utilities/patchUserExperience.js

Fixed some api calls that were incorrectly written.

fixed api routes

---

src/utilities/patchUserExperience.js

Call to patchUserExperience was written incorrectly, fixed.

Corrected patchUserExperience

---

prisma/index.js
src/components/Community.jsx
src/components/MyExperiences.jsx
src/components/NewExperience.jsx
src/components/SingleButcher.jsx

- Changed post experience so only one meat can be chosen
- Changed backend route to account for type change
- Changed code in other components to account for type change

Troubleshooting branch

---

prisma/schema.prisma

Changed meat type to string in schema

changed schema type

---

prisma/index.js
src/components/Community.jsx
src/components/MyExperiences.jsx
src/components/NewExperience.jsx
src/components/SingleButcher.jsx

Reverted changes to experience creation

Reverted experience changes

---

netlify.toml
prisma/schema.prisma

-Added folder to account for redirects in Netlify.

redirects for netlify

---

prisma/seed.js
src/components/Footer.jsx

- Added footer with our information
- Reworked seed to delete previous butchers and meats to properly update their images

added footer info / changed seed

---

prisma/seed.js

Changed order so butcherMeats get deleted first

switched order of deletes in seed

---

src/components/MeatYourMatch.jsx

Changed the way that meat your match finds the ID for the respective meats and butchers.

FIXED meat your match

---

src/components/Footer.jsx

Footer links now open in a new tab

Footer links open in a new tab
